version: 2.1

references:
  docker_hub_authentication: &docker_hub_authentication
    auth:
      username: $DOCKERHUB_USER
      password: $DOCKERHUB_PASSWORD

jobs:
  build:
    docker:
      - image: circleci/php:7.4-zts
        <<: *docker_hub_authentication
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: circleci/php:7.4-zts
        <<: *docker_hub_authentication
    steps:
      - checkout
      - run: echo "this is the test job"

# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - test
