version: 2.1

references:
  docker_hub_authentication: &docker_hub_authentication
    auth:
      username: $DOCKERHUB_USER
      password: $DOCKERHUB_PASSWORD

jobs:
  build:
    docker:
      - image: circleci/php:7.4-zts
        <<: *docker_hub_authentication
    steps:
      - checkout
      - run: echo "this is the build job"
  build-and-test:
    docker:
      - image: circleci/php:7.4-zts
        <<: *docker_hub_authentication
        environment:
          APP_ENV: testing
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_DATABASE: photo_sharing
      - image: mysql:5.7
        command: [ --character-set-server=utf8, --collation-server=utf8_general_ci, --sql_mode=NO_ENGINE_SUBSTITUTION ]
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_DATABASE: photo_sharing
          MYSQL_ALLOW_EMPTY_oASSWORD: yes
    working_directory: ~/workspace
    steps:
      - checkout



# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - test
